"""Codes d'erreurs stables + helper de logs classes."""

from __future__ import annotations

import logging
from dataclasses import dataclass


ERROR_TYPE_NETWORK = "network"
ERROR_TYPE_PARSE = "parse"
ERROR_TYPE_DATA = "data"
ERROR_TYPE_IO = "io"


@dataclass(frozen=True)
class ErrorCode:
    code: str
    error_type: str


# Network
NET_TIMEOUT_RETRY = ErrorCode("NET_TIMEOUT_RETRY", ERROR_TYPE_NETWORK)
NET_TIMEOUT_GIVEUP = ErrorCode("NET_TIMEOUT_GIVEUP", ERROR_TYPE_NETWORK)
NET_HTTP_429_RETRY = ErrorCode("NET_HTTP_429_RETRY", ERROR_TYPE_NETWORK)
NET_HTTP_5XX_RETRY = ErrorCode("NET_HTTP_5XX_RETRY", ERROR_TYPE_NETWORK)
NET_HTTP_404 = ErrorCode("NET_HTTP_404", ERROR_TYPE_NETWORK)
NET_HTTP_410 = ErrorCode("NET_HTTP_410", ERROR_TYPE_NETWORK)
NET_REQUEST_RETRY = ErrorCode("NET_REQUEST_RETRY", ERROR_TYPE_NETWORK)
NET_REQUEST_GIVEUP = ErrorCode("NET_REQUEST_GIVEUP", ERROR_TYPE_NETWORK)

# Parse
PARSE_SELECTOR_MISS = ErrorCode("PARSE_SELECTOR_MISS", ERROR_TYPE_PARSE)
PARSE_JSONLD_INVALID = ErrorCode("PARSE_JSONLD_INVALID", ERROR_TYPE_PARSE)
PARSE_PRICE_INVALID = ErrorCode("PARSE_PRICE_INVALID", ERROR_TYPE_PARSE)
PARSE_RATING_INVALID = ErrorCode("PARSE_RATING_INVALID", ERROR_TYPE_PARSE)
PARSE_CATEGORY_PAGE_FAILED = ErrorCode("PARSE_CATEGORY_PAGE_FAILED", ERROR_TYPE_PARSE)
PARSE_ZERO_CATEGORIES = ErrorCode("PARSE_ZERO_CATEGORIES", ERROR_TYPE_PARSE)
PARSE_ZERO_BOOKS = ErrorCode("PARSE_ZERO_BOOKS", ERROR_TYPE_PARSE)
PARSE_HIGH_ERROR_RATE = ErrorCode("PARSE_HIGH_ERROR_RATE", ERROR_TYPE_PARSE)

# Data
DATA_INVALID_TITLE = ErrorCode("DATA_INVALID_TITLE", ERROR_TYPE_DATA)
DATA_INVALID_PRICE = ErrorCode("DATA_INVALID_PRICE", ERROR_TYPE_DATA)
DATA_INVALID_RATING = ErrorCode("DATA_INVALID_RATING", ERROR_TYPE_DATA)
DATA_HIGH_CATEGORY_FAILURE_RATE = ErrorCode("DATA_HIGH_CATEGORY_FAILURE_RATE", ERROR_TYPE_DATA)

# IO / runtime
IO_ATOMIC_WRITE_FAILED = ErrorCode("IO_ATOMIC_WRITE_FAILED", ERROR_TYPE_IO)
IO_QUARANTINE_WRITE_FAILED = ErrorCode("IO_QUARANTINE_WRITE_FAILED", ERROR_TYPE_IO)
IO_LOCK_ACQUIRE_FAILED = ErrorCode("IO_LOCK_ACQUIRE_FAILED", ERROR_TYPE_IO)
IO_FAILED_HTML_CAPTURE = ErrorCode("IO_FAILED_HTML_CAPTURE", ERROR_TYPE_IO)
IO_STATE_READ_FAILED = ErrorCode("IO_STATE_READ_FAILED", ERROR_TYPE_IO)
IO_STATE_WRITE_FAILED = ErrorCode("IO_STATE_WRITE_FAILED", ERROR_TYPE_IO)
IO_ALERT_SEND_FAILED = ErrorCode("IO_ALERT_SEND_FAILED", ERROR_TYPE_IO)


def log_with_code(
    logger: logging.Logger,
    level: int,
    error: ErrorCode,
    message: str,
    *args: object,
    exc_info: bool = False,
) -> None:
    logger.log(
        level,
        "[error_type=%s error_code=%s] " + message,
        error.error_type,
        error.code,
        *args,
        exc_info=exc_info,
    )
